// Auto-generated image list - DO NOT EDIT MANUALLY
const basePath = 'Webp/';
const webpFiles = [
    "0.webp",
    "000011 copy.webp",
    "000018 copy.webp",
    "000020 copy.webp",
    "000032 copy.webp",
    "001.webp",
    "002.webp",
    "003.webp",
    "004.webp",
    "005.webp",
    "1 (2).webp",
    "1.webp",
    "2.webp",
    "2023-11-20_173527.webp",
    "2023-11-20_174905 (2).webp",
    "2023-11-20_180653 (2).webp",
    "3.webp",
    "6.webp",
    "7.webp",
    "7_Friendly Demon.webp",
    "80_1.webp",
    "80_2.webp",
    "80_3.webp",
    "A5.webp",
    "Around.webp",
    "BNOCS copy.webp",
    "Castle_v008.webp",
    "Castle_v011 copy.webp",
    "Cloud Dragon.webp",
    "Croxibition.webp",
    "Daniel_Pianiel.webp",
    "DarkmagicAuraCore.webp",
    "DeadDuck.webp",
    "Deorsus.webp",
    "DoBe2.webp",
    "DoBe3.webp",
    "Document_2023-11-20_180525.webp",
    "E001-1.webp",
    "E001-2.webp",
    "E001.webp",
    "E002.webp",
    "E003.webp",
    "Eggy Lads.webp",
    "FACE.webp",
    "Final_Day.webp",
    "Final_Night.webp",
    "FireGroup_2.webp",
    "Frame 1.webp",
    "Frame 2.webp",
    "Frame 7.webp",
    "Gronklet copy.webp",
    "Group 105.webp",
    "Group 106.webp",
    "Group 107.webp",
    "Group 24.webp",
    "Hair Party.webp",
    "Handwritten_2023-11-20_173755 (3).webp",
    "Handwritten_2023-11-20_180447 (10).webp",
    "Handwritten_2023-11-20_180744 (12).webp",
    "Huggins-1 copy.webp",
    "ISO_7010_W024 1.webp",
    "ITUNES2.webp",
    "Insta1.webp",
    "Insta2.webp",
    "Insta2a.webp",
    "Insta3.webp",
    "Invite-1.webp",
    "Logos.webp",
    "Magnet&Star.webp",
    "NOTO copy2.webp",
    "NR-Skratch.webp",
    "NS.webp",
    "Nathans Room Hero copy.webp",
    "Newtenoged2.webp",
    "Peeps.webp",
    "PhyllotaxisGalaxis.webp",
    "Psychic Damage Warning Sticker.svg",
    "Shirt Popup.webp",
    "Sklob_The Great copy 2.webp",
    "Skullboy.jpg",
    "Starjump pillars 4.webp",
    "Stellus Heretica.webp",
    "The Nighthelmets.webp",
    "The angel ball.webp",
    "VisitingEbrith-0.webp",
    "VisitingEbrith-2.webp",
    "Ylsador.webp",
    "ZIA-1.webp",
    "bb.webp",
    "glassboi_LightLines.webp",
    "months.webp",
    "nate_2.webp",
    "noto2 copy.webp",
    "untitled.webp",
    "yeahyougotthatYUMMI.webp"
];
const fullPathWebpFiles = webpFiles.map(file => basePath + encodeURIComponent(file));
